float_params:
- high: 0.1
  log: true
  low: 0.001
  name: learning_rate
- high: 0.75
  low: 0.1
  name: feature_fraction
int_params:
- high: 10
  log: false
  low: 3
  name: num_trees
- high: 10
  low: 3
  name: max_depth
- high: 25
  low: 5
  name: num_leaves
objective_values: mean
