EXPERIMENT_ID: '255253755991586970'
RUN_ID: 37cff3aa004b4ce39824c97d3f957fb5
date_features:
- month
- dayofweek
- hour
forecast_horizon: 48
freq: H
hpo_config_version: 1
id_col: prediction_unit_id
model_name: lightgbm
n_lag_transforms: 4
n_lags: 4
n_splits: 5
n_trials: 3
random_state: 0
rolling_mean_window_size: 4
s3_bucket: null
scoring: neg_mean_absolute_error
splitting_datetime: 2023-01-26 05:00:00
static_features:
- county
- is_business
- product_type
- is_consumption
- prediction_unit_id
studies_dir: ./optuna_studies
target_col: target
time_col: datetime
