# preprocessing
splitting_datetime: 2023-01-26 05:00:00
# feature engineering
freq: H
id_col: prediction_unit_id
time_col: datetime
target_col: target
forecast_horizon: 48
n_lags: &n_lags 4
rolling_mean_window_size: 4
date_features: ["month", "dayofweek", "hour"]
static_features: ["county", "is_business", "product_type", "is_consumption", "prediction_unit_id"]
n_lag_transforms: *n_lags
# HPO
model_name: lightgbm
hpo_config_version: 1
random_state: 0
n_splits: 5 # number of CV splits
scoring: neg_mean_absolute_error # scoring for CV
n_trials: 3
studies_dir: ./optuna_studies
# sync with S3
s3_bucket: # '%env:S3_BUCKET%'
# aws_access_key_id='%env:AWS_ACCESS_KEY_ID%'