splitting_datetime: 2023-01-26 05:00:00

forecast_horizon: 48
freq: H
id_col: prediction_unit_id
time_col: datetime
target_col: target
lags: [48, 72, 96, 120, 144, 168]
lag_transforms_index: [48]
rolling_mean_window_sizes: [6, 12, 24, 48]
date_features: [month, dayofweek, hour]
static_features:
- county
- is_business
- product_type
- is_consumption
- prediction_unit_id

model_name: lightgbm
hpo_config_version: 1
n_splits: 5
n_trials: 3
random_state: 0

s3_bucket: null
scoring: neg_mean_absolute_error
studies_dir: ./optuna_studies
